// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel': string;
  'carousel-scrollbar-hide': string;
  'carouselContainer': string;
  'carouselFrame': string;
  'carouselFramePadded': string;
  'carouselScrollbarHide': string;
  'carouselSkip': string;
  'carousel__container': string;
  'carousel__frame': string;
  'carousel__frame--padded': string;
  'carousel__skip': string;
}
declare var cssExports: CssExports;
export = cssExports;
