// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'controls-row': string;
  'controlsRow': string;
  'example-slide': string;
  'example-slide__link': string;
  'exampleSlide': string;
  'exampleSlideLink': string;
}
declare var cssExports: CssExports;
export = cssExports;
