// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel-arrow': string;
  'carousel-arrow--left': string;
  'carousel-arrow--right': string;
  'carouselArrow': string;
  'carouselArrowLeft': string;
  'carouselArrowRight': string;
}
declare var cssExports: CssExports;
export = cssExports;
