// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel-page': string;
  'carousel-page--current': string;
  'carousel-pagination': string;
  'carousel-pagination--numbers': string;
  'carouselPage': string;
  'carouselPageCurrent': string;
  'carouselPagination': string;
  'carouselPaginationNumbers': string;
}
declare var cssExports: CssExports;
export = cssExports;
