// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'carousel-slide': string;
  'carousel-slide--padded': string;
  'carousel-slide-container': string;
  'carouselSlide': string;
  'carouselSlideContainer': string;
  'carouselSlidePadded': string;
}
declare var cssExports: CssExports;
export = cssExports;
